### PR TITLE
Express structure built & Created API samples

### PR DESCRIPTION
**Pull request by robeartoe**
Created the Express structure for the project. HTML & CSS is ready to be created.

Also created a few samples, API's are ready to be tested on node. Maps API has to work on a HTML page, so I'm not quite sure yet how to create a sample for that.

### CODE REVIEW

**Comment by thelonster** [comment]
This looks great, thanks Robert

**Comment by thelonster** [comment]
GitHub is showing me that we have vulnerabilities in our dependencies, specifically with hapijs/cryptiles and  hapijs/hoek. GitHub is recommending me to change them from v 2.0.5 -> v 4.1.2 for cryptiles and v 2.16.3 -> 4.1.2

**Comment by robeartoe** [comment]
From the looks of it, there is a vulnerability. Check [here](https://github.com/hapijs/hoek/issues/247). 

Though, from what I'm reading it's not as bad as they make it seem.

Those two packages are dependencies of another package. So I'm not sure if it's ok to update these dependencies without breaking a few. I will test this out when I get some free time.

**Comment by thelonster** [comment]
Yeah it doesn't seem to be that bad. If it's too difficult to update, don't worry about it. I'm just going to ignore the warning for the time being.

**Pull request merged**
